apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditmanager
  labels:
    app: creditmanager
  namespace: default
spec:
  selector:
    matchLabels:
      app: creditmanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: creditmanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/creditmanager:latest
        imagePullPolicy: Always
        name: creditmanager
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: creditmanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creditmanager
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99