apiVersion: v1
kind: Namespace
metadata:
  name: creditmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditmanager
  namespace: creditmanager
  labels:
    app: creditmanager
spec:
  selector:
    matchLabels:
      app: creditmanager
  template:
    metadata:
      labels:
        app: creditmanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/creditmanager:latest
        imagePullPolicy: Always
        name: creditmanager
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: creditmanager
  namespace: creditmanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: creditmanager
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 50
